---

- name: create exchanges
  rabbitmq_exchange:
    vhost: "{{ item.0.name | default(item.1.vhost)"
    name: "{{ item.1.name }}"
    state: "{{ item.1.state | default('present') }}"
    durable: "{{ item.1.durable | defautl('yes') }}"
    exchange_type: "{{ item.1.exchange_type | default('direct') }}"
    auto_delete: "{{ item.1.auto_delete | default('no') }}"
    login_host: "{{ item.1.login_host | default('localhost') }}"
    login_port: "{{ item.1.login_port | default(15672) }}"
    login_user: "{{ item.0.rabbitmq_users[0].user }}"
    login_password: "{{ item.0.rabbitmq_users[0].password }}"
  with_nested:
    - "{{ vhosts }}"
    - "{{ rabbitmq_exchanges }}"
