---

- name: Manage RabbitMQ policies
  rabbitmq_policy:
    name: '{{ item.1.name }}'
    apply_to: '{{ item.1.apply_to | default("all") }}'
    pattern: '{{ item.1.pattern | default(".*") }}'
    vhost: '{{ item.0.name | default("/") }}'
    state: '{{ item.1.state | default("present") }}'
    tags: '{{ item.1.tags | default({}) }}'
    node: 'rabbit@{{ ansible_hostname }}'
    priority: '{{ item.1.priority | default(0) }}'
  with_subelements:
    - "{{ vhosts }}"
    - rabbitmq_policies
