---

- name: Manage RabbitMQ policies
  rabbitmq_policy:
    name: '{{ item.1.name }}'
    pattern: '{{ item.1.pattern | default(".*") }}'
    vhost: '{{ item.1.vhost | default("/") }}'
    state: '{{ item.1.state | default("present") }}'
    tags: '{{ item.1.tags | default({}) }}'
    node: '{{ rabbitmq_cluster_name }}@{{ ansible_hostname }}'
  with_subelements:
    - "{{ vhosts }}"
    - rabbitmq_policies
