---

- name: prefligth | check variables
  fail:
    msg: "external_endpoint variable is required if federation enabled."
  when: >
    rabbitmq_federation
    and hostvars[inventory_hostname][ hostvars[inventory_hostname].rabbitmq_cluster_name ].external_endpoint is not defined

- name: preflight | load vhosts configuration
  include_vars:
    dir: "vars/vhost/"
    name: vhosts
    ignore_unknown_extensions: yes
    extensions:
      - 'yaml'
      - 'yml'

- name: preflight | show vhosts config
  debug:
    msg: " vhost={{ item }}, users = {{ vhosts[item]['rabbitmq_users'] }}, policies={{ vhosts[item]['rabbitmq_policies'] }} "
  with_items: "{{ vhosts }}"
