---

- name: Manage RabbitMQ users and privileges
  rabbitmq_user:
    user: '{{ item.1.user }}'
    password: '{{ item.1.password | default("") }}'
    vhost: '{{ item.0.name | default("/") }}'
    node: 'rabbit@{{ ansible_hostname }}'
    tags: '{{ (item.1.tags | default("")) | join(",") }}'
    configure_priv: '{{ item.1.configure_priv | default(".*") }}'
    read_priv: '{{ item.1.read_priv | default(".*") }}'
    write_priv: '{{ item.1.write_priv | default(".*") }}'
    state: '{{ item.1.state | default("present") }}'
    force: '{{ item.1.force | default("no") }}'
  with_subelements:
    - "{{ vhosts }}"
    - rabbitmq_users
