---

- name: Add RabbitMQ vhosts
  rabbitmq_vhost:
    name: '{{ vhosts[item].name }}'
    node: 'rabbit@{{ ansible_hostname }}'
    state: '{{ vhosts[item].state | default("present") }}'
    tracing: '{{ vhosts[item].tracing | default("no") }}'
  with_items: '{{ vhosts }}'
