---
- name: Converge
  hosts: all
  connection: local
  vars:

    rabbitmq_cluster: true
    rabbitmq_cluster_name: r1
    rabbitmq_ssl: no
    rabbitmq_ssl_cluster: no
    rabbitmq_plugins:
      - rabbitmq_management
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_prometheus
      - rabbitmq_shovel
      - rabbitmq_shovel_management
  tasks:
    - name: "Include ansible-rabbitmq-configuration"
      include_role:
        name: "ansible-rabbitmq-configuration"
